# Generated by Django 3.2.7 on 2021-09-30 07:13

from django.db import migrations, models

def create_data(apps, schema_editor):
    Testing = apps.get_model('testing', 'Testing')
    Testing(name="First Test".save())

class Migration(migrations.Migration):

    initial = True

    # dependencies = [
    #     ('testing')
    # ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
            ],
        ),
        migrations.RunPython(create_data)
    ]
