# Generated by Django 3.2.7 on 2021-10-15 20:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3), size=7),
        ),
    ]
