# Generated by Django 3.2.7 on 2021-10-01 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_list',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
