# Generated by Django 3.2.7 on 2021-10-09 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf_users', '0002_auto_20211009_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_list',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
