# Generated by Django 3.2.7 on 2021-10-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf_users', '0002_user_friend_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
