# Generated by Django 3.2.7 on 2021-10-20 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sf_users', '0002_alter_course_day_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='owner',
        ),
    ]
