# Generated by Django 3.2.7 on 2021-10-01 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sf_users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sf_users.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sf_users.day'),
        ),
    ]
