# Generated by Django 3.2.7 on 2021-11-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf_users', '0003_rename_user_course_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_request'),
        ),
    ]
