# Generated by Django 3.2.7 on 2021-10-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf_users', '0004_alter_user_friend_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='pending_requests',
            field=models.ManyToManyField(blank=True, to='sf_users.FriendRequest'),
        ),
    ]
