# Generated by Django 3.2.7 on 2021-11-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf_users', '0005_auto_20211101_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, default=None, to='sf_users.FriendRequest'),
        ),
    ]
