# Generated by Django 3.2.7 on 2021-10-05 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sf_users', '0005_auto_20211005_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='schedule',
        ),
        migrations.AddField(
            model_name='course',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sf_users.day'),
        ),
        migrations.AddField(
            model_name='day',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
