# Generated by Django 3.2.7 on 2021-10-10 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sf_users', '0005_auto_20211009_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pending_requests',
            new_name='friend_requests',
        ),
    ]
