# Generated by Django 3.2.7 on 2021-11-21 08:17

from django.db import migrations, models
import sf_users.models


class Migration(migrations.Migration):

    dependencies = [
        ('sf_users', '0006_user_friend_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='pimages/default.jpg', upload_to=sf_users.models.upload_to, verbose_name='Image'),
        ),
    ]
