# Generated by Django 3.2.7 on 2021-10-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sf_users', '0006_auto_20211005_0549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
