# Generated by Django 3.2.7 on 2021-12-04 18:02

import django.core.validators
from django.db import migrations, models
import sf_users.models


class Migration(migrations.Migration):

    dependencies = [
        ('sf_users', '0007_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to=sf_users.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_end',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^([0-1][0-9]|2[0-3]):[0-5][0-9]$', 'Time must be [00-24]:[00-59] input')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_start',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^([0-1][0-9]|2[0-3]):[0-5][0-9]$', 'Time must be [00-24]:[00-59] input')]),
        ),
    ]
