# Generated by Django 3.2.7 on 2021-10-05 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sf_users', '0007_delete_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day',
            new_name='day_name',
        ),
        migrations.RemoveField(
            model_name='day',
            name='schedule',
        ),
        migrations.AddField(
            model_name='day',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to=settings.AUTH_USER_MODEL),
        ),
    ]
