# Generated by Django 3.2.7 on 2021-12-05 06:29

from django.db import migrations, models
import sf_users.models


class Migration(migrations.Migration):

    dependencies = [
        ('sf_users', '0008_auto_20211204_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_images/default_kqav0k.jpg', upload_to=sf_users.models.upload_to, verbose_name='Image'),
        ),
    ]
