# Generated by Django 3.2.7 on 2021-10-05 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sf_users', '0008_auto_20211005_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_number', models.CharField(max_length=30)),
                ('time_start', models.CharField(max_length=7)),
                ('time_end', models.CharField(max_length=7)),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='sf_users.day')),
            ],
        ),
    ]
